### ISSUE TITLE
DELEG is no longer a BoF

### ISSUE THREAD

**Issue by dhruvdhody** [InternetSociety/IETF-Ornithology#2]
deleg is already a working group - https://datatracker.ietf.org/group/deleg/about/

Perhaps - the newly formed WG could be another section?

**Comment by Kolkman** [comment]
Thanks Dhruv.

I moved the deleg description to the 'archive' (out of the document), as it seems there are no direct public policy implications. (I have a slight doubt there: does this work potential the balance of power within the DNS business ecosystem?, I'd welcome your thoughts there.


On the idea of newly formed WG  - maybe a summary of those.

**Comment by Kolkman** [comment]
There will be a new working group section under the IETF chapter for the next version. 

Closing this issue
